// Configuration for Bedrock Agent Chatbot
// This file is auto-generated by Terraform
const config = {
  aws: {
    region: 'us-east-1',
    identityPoolId: 'us-east-1:298d8fe3-cde3-4481-a8ec-03ae1587a5bd',
  },
  cognito: {
    userPoolId: 'us-east-1_YCE3XlPmi',
    userPoolClientId: 'fejr1pv22l4lp81b22f1am6lf',
  },
  bedrock: {
    agentId: 'SK780TVUNL',
    agentAliasId: 'EDHYCPPPEW',
  },
  fileUpload: {
    apiUrl: 'https://mlp99fhcbh.execute-api.us-east-1.amazonaws.com/prod/upload',
  },
  dynamodb: {
    conversationsTable: 'pecarn-conversations-dev',
    messagesTable: 'pecarn-messages-dev',
  },
  app: {
    title: 'Pecarn Agent Chatbot',
    description: 'AI-powered chatbot using Amazon Bedrock Agent',
    loginSubtitle: 'Sign in to start chatting with our AI assistant',
    inputPlaceholder: 'Ask me anything... (Shift+Enter for new line)',
    tips: 'Ask questions to get helpful responses',
    shortcuts: 'Enter to send • Shift+Enter for new line'
  }
};

export default config;
